export const listCountries = [
  {"name": "Albanie", "code": "AL"},
  {"name": "Algerie", "code": "DZ"},
  {"name": "Allemagne", "code": "DE"},
  {"name": "Andorre", "code": "AD"},
  {"name": "Argentine", "code": "AR"},
  {"name": "Autriche", "code": "AT"},
  {"name": "Belgique", "code": "BE"},
  {"name": "Bolivie", "code": "BO"},
  {"name": "Brésil", "code": "BR"},
  {"name": "Bulgarie", "code": "BG"},
  {"name": "Canada", "code": "CA"},
  {"name": "Chile", "code": "CL"},
  {"name": "Chypre", "code": "CY"},
  {"name": "Colombie", "code": "CO"},
  {"name": "Costa Rica", "code": "CR"},
  {"name": "Croatie", "code": "HR"},
  {"name": "Danemark", "code": "DK"},
  {"name": "Espagne", "code": "ES"},
  {"name": "Estonie", "code": "EE"},
  {"name": "Etats-Unis", "code": "US"},
  {"name": "Finlande", "code": "FI"},
  {"name": "France", "code": "FR"},
  {"name": "Gibraltar", "code": "GI"},
  {"name": "Grèce", "code": "GR"},
  {"name": "Guadeloupe", "code": "GP"},
  {"name": "Guatemala", "code": "GT"},
  {"name": "Guyane", "code": "GY"},
  {"name": "Guyane Française", "code": "GF"},
  {"name": "Hongrie", "code": "HU"},
  {"name": "Irlande", "code": "IR"},
  {"name": "Islande", "code": "IS"},
  {"name": "Israël", "code": "ISR"},
  {"name": "Italie", "code": "IT"},
  {"name": "La Réunion", "code": "LR"},
  {"name": "Lettonie", "code": "LT"},
  {"name": "Liban", "code": "LR"},
  {"name": "Liechtenstein", "code": "LI"},
  {"name": "Lituanie", "code": "LIT"},
  {"name": "Luxembourg", "code": "LU"},
  {"name": "Malte", "code": "MT"},
  {"name": "Maroc", "code": "MA"},
  {"name": "Martinique", "code": "MQ"},
  {"name": "Mayotte", "code": "YT"},
  {"name": "Mexique", "code": "MX"},
  {"name": "Moldavie", "code": "MD"},
  {"name": "Monaco", "code": "MC"},
  {"name": "Norvège", "code": "NO"},
  {"name": "Nouvelle-Calédonie", "code": "NC"},
  {"name": "Panama", "code": "PA"},
  {"name": "Paraguay", "code": "PY"},
  {"name": "Pays-Bas", "code": "PB"},
  {"name": "Pologne", "code": "PL"},
  {"name": "Portugal", "code": "PT"},
  {"name": "Puerto Rico", "code": "PR"},
  {"name": "Pérou", "code": "PO"},
  {"name": "Roumanie", "code": "RO"},
  {"name": "Royaume-Uni (UK)", "code": "RU"},
  {"name": "République Tchèque", "code": "RT"},
  {"name": "Saint Pierre et Miquelon", "code": "PM"},
  {"name": "Salvador", "code": "VC"},
  {"name": "Slovaquie", "code": "SK"},
  {"name": "Slovenie", "code": "SI"},
  {"name": "Suisse", "code": "SB"},
  {"name": "Suède", "code": "SO"},
  {"name": "Terres Australes Françaises", "code": "TW"},
  {"name": "Tunisie", "code": "TJ"},
  {"name": "Ukraine", "code": "UA"},
  {"name": "Uruguay", "code": "UY"},
  {"name": "Vatican", "code": "VU"},
  {"name": "Venezuela", "code": "VE"},
  {"name": "Equateur", "code": "EQ"},
]
