export const listCountries = [
  {"name": "Albanie", "value": "AL"},
  {"name": "Algerie", "value": "DZ"},
  {"name": "Allemagne", "value": "DE"},
  {"name": "Andorre", "value": "AD"},
  {"name": "Argentine", "value": "AR"},
  {"name": "Autriche", "value": "AT"},
  {"name": "Belgique", "value": "BE"},
  {"name": "Bolivie", "value": "BO"},
  {"name": "Brésil", "value": "BR"},
  {"name": "Bulgarie", "value": "BG"},
  {"name": "Canada", "value": "CA"},
  {"name": "Chile", "value": "CL"},
  {"name": "Chypre", "value": "CY"},
  {"name": "Colombie", "value": "CO"},
  {"name": "Costa Rica", "value": "CR"},
  {"name": "Croatie", "value": "HR"},
  {"name": "Danemark", "value": "DK"},
  {"name": "Espagne", "value": "ES"},
  {"name": "Estonie", "value": "EE"},
  {"name": "Etats-Unis", "value": "US"},
  {"name": "Finlande", "value": "FI"},
  {"name": "France", "value": "FR"},
  {"name": "Gibraltar", "value": "GI"},
  {"name": "Grèce", "value": "GR"},
  {"name": "Guadeloupe", "value": "GP"},
  {"name": "Guatemala", "value": "GT"},
  {"name": "Guyane", "value": "GY"},
  {"name": "Guyane Française", "value": "GF"},
  {"name": "Hongrie", "value": "HU"},
  {"name": "Irlande", "value": "IR"},
  {"name": "Islande", "value": "IS"},
  {"name": "Israël", "value": "ISR"},
  {"name": "Italie", "value": "IT"},
  {"name": "La Réunion", "value": "LR"},
  {"name": "Lettonie", "value": "LT"},
  {"name": "Liban", "value": "LB"},
  {"name": "Liechtenstein", "value": "LI"},
  {"name": "Lituanie", "value": "LIT"},
  {"name": "Luxembourg", "value": "LU"},
  {"name": "Malte", "value": "MT"},
  {"name": "Maroc", "value": "MA"},
  {"name": "Martinique", "value": "MQ"},
  {"name": "Mayotte", "value": "YT"},
  {"name": "Mexique", "value": "MX"},
  {"name": "Moldavie", "value": "MD"},
  {"name": "Monaco", "value": "MC"},
  {"name": "Norvège", "value": "NO"},
  {"name": "Nouvelle-Calédonie", "value": "NC"},
  {"name": "Panama", "value": "PA"},
  {"name": "Paraguay", "value": "PY"},
  {"name": "Pays-Bas", "value": "PB"},
  {"name": "Pologne", "value": "PL"},
  {"name": "Portugal", "value": "PT"},
  {"name": "Puerto Rico", "value": "PR"},
  {"name": "Pérou", "value": "PO"},
  {"name": "Roumanie", "value": "RO"},
  {"name": "Royaume-Uni (UK)", "value": "RU"},
  {"name": "République Tchèque", "value": "RT"},
  {"name": "Saint Pierre et Miquelon", "value": "PM"},
  {"name": "Salvador", "value": "VC"},
  {"name": "Slovaquie", "value": "SK"},
  {"name": "Slovenie", "value": "SI"},
  {"name": "Suisse", "value": "SB"},
  {"name": "Suède", "value": "SO"},
  {"name": "Terres Australes Françaises", "value": "TW"},
  {"name": "Tunisie", "value": "TJ"},
  {"name": "Ukraine", "value": "UA"},
  {"name": "Uruguay", "value": "UY"},
  {"name": "Vatican", "value": "VU"},
  {"name": "Venezuela", "value": "VE"},
  {"name": "Equateur", "value": "EQ"},
]
